/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BuyersRouteImport } from './routes/buyers'
import { Route as FarmerRouteImport } from './routes/farmer'
import { Route as MarketRouteImport } from './routes/market'
import { Route as PricesRouteImport } from './routes/prices'
import { Route as ProcurementRouteImport } from './routes/procurement'
import { Route as QueueRouteImport } from './routes/queue'
import { Route as RegisterCropRouteImport } from './routes/register-crop'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyersRoute = BuyersRouteImport.update({
  id: '/buyers',
  path: '/buyers',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmerRoute = FarmerRouteImport.update({
  id: '/farmer',
  path: '/farmer',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketRoute = MarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => rootRouteImport,
} as any)
const PricesRoute = PricesRouteImport.update({
  id: '/prices',
  path: '/prices',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcurementRoute = ProcurementRouteImport.update({
  id: '/procurement',
  path: '/procurement',
  getParentRoute: () => rootRouteImport,
} as any)
const QueueRoute = QueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterCropRoute = RegisterCropRouteImport.update({
  id: '/register-crop',
  path: '/register-crop',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/buyers': typeof BuyersRoute
  '/farmer': typeof FarmerRoute
  '/market': typeof MarketRoute
  '/prices': typeof PricesRoute
  '/procurement': typeof ProcurementRoute
  '/queue': typeof QueueRoute
  '/register-crop': typeof RegisterCropRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/buyers': typeof BuyersRoute
  '/farmer': typeof FarmerRoute
  '/market': typeof MarketRoute
  '/prices': typeof PricesRoute
  '/procurement': typeof ProcurementRoute
  '/queue': typeof QueueRoute
  '/register-crop': typeof RegisterCropRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/buyers': typeof BuyersRoute
  '/farmer': typeof FarmerRoute
  '/market': typeof MarketRoute
  '/prices': typeof PricesRoute
  '/procurement': typeof ProcurementRoute
  '/queue': typeof QueueRoute
  '/register-crop': typeof RegisterCropRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/buyers'
    | '/farmer'
    | '/market'
    | '/prices'
    | '/procurement'
    | '/queue'
    | '/register-crop'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/buyers'
    | '/farmer'
    | '/market'
    | '/prices'
    | '/procurement'
    | '/queue'
    | '/register-crop'
  id:
    | '__root__'
    | '/'
    | '/buyers'
    | '/farmer'
    | '/market'
    | '/prices'
    | '/procurement'
    | '/queue'
    | '/register-crop'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BuyersRoute: typeof BuyersRoute
  FarmerRoute: typeof FarmerRoute
  MarketRoute: typeof MarketRoute
  PricesRoute: typeof PricesRoute
  ProcurementRoute: typeof ProcurementRoute
  QueueRoute: typeof QueueRoute
  RegisterCropRoute: typeof RegisterCropRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buyers': {
      id: '/buyers'
      path: '/buyers'
      fullPath: '/buyers'
      preLoaderRoute: typeof BuyersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmer': {
      id: '/farmer'
      path: '/farmer'
      fullPath: '/farmer'
      preLoaderRoute: typeof FarmerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market': {
      id: '/market'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof MarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prices': {
      id: '/prices'
      path: '/prices'
      fullPath: '/prices'
      preLoaderRoute: typeof PricesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/procurement': {
      id: '/procurement'
      path: '/procurement'
      fullPath: '/procurement'
      preLoaderRoute: typeof ProcurementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/queue': {
      id: '/queue'
      path: '/queue'
      fullPath: '/queue'
      preLoaderRoute: typeof QueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register-crop': {
      id: '/register-crop'
      path: '/register-crop'
      fullPath: '/register-crop'
      preLoaderRoute: typeof RegisterCropRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BuyersRoute: BuyersRoute,
  FarmerRoute: FarmerRoute,
  MarketRoute: MarketRoute,
  PricesRoute: PricesRoute,
  ProcurementRoute: ProcurementRoute,
  QueueRoute: QueueRoute,
  RegisterCropRoute: RegisterCropRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
